// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWdQOIVWkz9J93thEke1f9rZjKHubtROg',
    appId: '1:185993262437:web:6033814bd32a8bd6b31d8c',
    messagingSenderId: '185993262437',
    projectId: 'expensely-app',
    authDomain: 'expensely-app.firebaseapp.com',
    storageBucket: 'expensely-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Mr8gbA4pnLBWBZlJi4iDuf1CtgCZ2Cs',
    appId: '1:185993262437:android:bb7ece181d58c8bdb31d8c',
    messagingSenderId: '185993262437',
    projectId: 'expensely-app',
    storageBucket: 'expensely-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-5AK7FXlXRLoP8Oxn1UfJysnFpI877is',
    appId: '1:185993262437:ios:59a28cf46526ac14b31d8c',
    messagingSenderId: '185993262437',
    projectId: 'expensely-app',
    storageBucket: 'expensely-app.firebasestorage.app',
    iosBundleId: 'com.ambdulghaffar.expenselyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-5AK7FXlXRLoP8Oxn1UfJysnFpI877is',
    appId: '1:185993262437:ios:59a28cf46526ac14b31d8c',
    messagingSenderId: '185993262437',
    projectId: 'expensely-app',
    storageBucket: 'expensely-app.firebasestorage.app',
    iosBundleId: 'com.ambdulghaffar.expenselyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWdQOIVWkz9J93thEke1f9rZjKHubtROg',
    appId: '1:185993262437:web:be5e12098e1859ddb31d8c',
    messagingSenderId: '185993262437',
    projectId: 'expensely-app',
    authDomain: 'expensely-app.firebaseapp.com',
    storageBucket: 'expensely-app.firebasestorage.app',
  );
}
